//! Device transfer: moving everything that makes this phone *this* phone to a
//! replacement — the identity key, the per-email-key conversations, and the
//! app's archive of forward-secret mail.
//!
//! `docs/superpowers/specs/2026-09-19-per-email-keys-design.md`, "Device
//! transfer".
//!
//! # What travels
//!
//! One text file, sealed under a code the old phone shows once:
//!
//! - the identity key, re-locked under the code exactly as a recovery backup is
//!   (`recovery.rs`), so it is never unlocked outside a core;
//! - every session-store record — this device's offers, each conversation, each
//!   contact's offer — opened from this install's key and resealed under the
//!   new one's on arrival;
//! - the archive, which the TypeScript side hands in as an opaque string: the
//!   decrypted copies of forward-secret mail are the only copies there are.
//!
//! # Moved, never copied
//!
//! Two phones sending from one conversation would each derive the same next
//! keys and advance them differently, and the contact could follow only one of
//! them. So exporting **hands the store over**: from then on the old phone
//! sends the old way and never rotates its offers. It can still *read* — a
//! receive step is deterministic, so both copies arrive at the same state from
//! the same message — which is what lets the user keep using it until the new
//! phone is set up.
//!
//! # The code, and why HKDF rather than Argon2
//!
//! The code is 32 random Crockford base32 characters — 160 bits, generated by
//! the app and never chosen by a person — so there is nothing for a slow hash
//! to protect: guessing it is out of reach at any speed. A short code is
//! refused outright, because that argument only holds for a random one.

use base64::{engine::general_purpose::STANDARD as B64, Engine};
use aes_gcm::aead::{Aead, KeyInit, Payload};
use aes_gcm::{Aes256Gcm, Nonce};
use hkdf::Hkdf;
use rand::{thread_rng, RngCore};
use serde::{Deserialize, Serialize};
use sha2::Sha256;
use std::path::Path;
use zeroize::Zeroizing;

use crate::identity::Identity;
use crate::session_store::SessionStore;
use crate::{recovery, CoreError, Result};

const BEGIN: &str = "-----BEGIN CRYPTMAIL TRANSFER-----";
const END: &str = "-----END CRYPTMAIL TRANSFER-----";
const VERSION: u8 = 1;
const AAD: &[u8] = b"cryptmail/v1/transfer";
/// 26 Crockford characters is 130 bits. Anything shorter was not generated by
/// the app, and HKDF is only sound for a code that was.
const MIN_CODE_CHARS: usize = 26;

#[derive(Serialize, Deserialize)]
struct Bundle {
    email: String,
    created: i64,
    /// The identity key, armored, locked under the code.
    key: String,
    /// `(record name, base64 of its JSON)`.
    sessions: Vec<(String, String)>,
    /// Opaque to the core — the app's archive.
    archive: String,
}

/// What an import hands back to the app.
#[derive(Serialize)]
pub struct Imported {
    pub identity: Identity,
    pub archive: String,
}

/// Seal this phone's identity, conversations and `archive` under `code`, then
/// mark the conversations handed over. Returns the armored file.
pub(crate) fn export(dir: &Path, email: &str, passphrase: &str, code: &str, archive: &str, now: i64) -> Result<String> {
    let code = checked(code)?;
    let key = recovery::export(dir, email, passphrase, &code)?;
    let store = SessionStore::open(dir, passphrase)?;
    let sessions = store
        .export_records()?
        .into_iter()
        .map(|(name, plain)| (name, B64.encode(&*plain)))
        .collect();

    let bundle = Bundle { email: email.trim().to_lowercase(), created: now, key, sessions, archive: archive.to_string() };
    let plain = Zeroizing::new(serde_json::to_vec(&bundle).map_err(|e| CoreError::Unavailable(e.to_string()))?);

    let mut rng = thread_rng();
    let mut salt = [0u8; 16];
    let mut nonce = [0u8; 12];
    rng.fill_bytes(&mut salt);
    rng.fill_bytes(&mut nonce);
    let sealed = cipher(&code, &salt)
        .encrypt(Nonce::from_slice(&nonce), Payload { msg: &plain, aad: AAD })
        .map_err(|_| CoreError::Unavailable("could not seal the transfer".into()))?;

    let body = B64.encode([&[VERSION][..], &salt, &nonce, &sealed].concat());
    let mut armored = format!("{BEGIN}\nComment: CryptMail device transfer — useless without its code\n\n");
    for line in body.as_bytes().chunks(64) {
        armored.push_str(std::str::from_utf8(line).expect("base64 is ASCII"));
        armored.push('\n');
    }
    armored.push_str(END);
    armored.push('\n');

    // Only once the file exists: a failure above leaves this phone as it was.
    store.hand_over(now)?;
    Ok(armored)
}

/// Adopt a transfer: the identity, then the conversations, replacing whatever
/// this phone held. `expected_email`, when not empty, is the mailbox signed in
/// here — a transfer for another address is refused before anything changes.
pub(crate) fn import(dir: &Path, passphrase: &str, armored: &str, code: &str, expected_email: &str) -> Result<Imported> {
    let payload = dearmor(armored)?;
    if payload.len() < 1 + 16 + 12 + 16 || payload[0] != VERSION {
        return Err(CoreError::Malformed("this transfer is damaged, or from a newer version of CryptMail".into()));
    }
    let code = checked(code).map_err(|_| wrong_code())?;
    let (salt, rest) = payload[1..].split_at(16);
    let (nonce, sealed) = rest.split_at(12);
    let plain = Zeroizing::new(
        cipher(&code, salt)
            .decrypt(Nonce::from_slice(nonce), Payload { msg: sealed, aad: AAD })
            .map_err(|_| wrong_code())?,
    );
    let bundle: Bundle =
        serde_json::from_slice(&plain).map_err(|_| CoreError::Malformed("this transfer is damaged".into()))?;

    let expected = expected_email.trim().to_lowercase();
    if !expected.is_empty() && bundle.email != expected {
        return Err(CoreError::Malformed(format!(
            "this transfer holds the key for {}, not {expected}",
            bundle.email
        )));
    }

    let mut records = Vec::with_capacity(bundle.sessions.len());
    for (name, encoded) in &bundle.sessions {
        let plain = B64
            .decode(encoded)
            .map_err(|_| CoreError::Malformed(format!("a transfer record is damaged ({name})")))?;
        records.push((name.clone(), plain));
    }
    let store = SessionStore::open(dir, passphrase)?;
    store.check_records(&records)?;

    let identity = recovery::import(dir, passphrase, &bundle.key, &code)?;
    store.replace_records(&records)?;
    for (_, plain) in &mut records {
        zeroize::Zeroize::zeroize(plain);
    }
    Ok(Imported { identity, archive: bundle.archive })
}

fn checked(code: &str) -> Result<String> {
    let code = recovery::normalise(code);
    if code.len() < MIN_CODE_CHARS {
        return Err(CoreError::Malformed("a transfer code is 32 characters".into()));
    }
    Ok(code)
}

fn cipher(code: &str, salt: &[u8]) -> Aes256Gcm {
    let mut key = Zeroizing::new([0u8; 32]);
    Hkdf::<Sha256>::new(Some(salt), code.as_bytes())
        .expand(b"cryptmail/v1/transfer key", &mut *key)
        .expect("32 bytes is a valid HKDF-SHA256 output length");
    Aes256Gcm::new_from_slice(&*key).expect("the transfer key is 32 bytes")
}

fn dearmor(text: &str) -> Result<Vec<u8>> {
    let not_one = || CoreError::Malformed("this is not a CryptMail transfer file".into());
    let start = text.find(BEGIN).ok_or_else(not_one)? + BEGIN.len();
    let end = text[start..].find(END).ok_or_else(not_one)? + start;
    let body: String = text[start..end]
        .lines()
        .filter(|line| !line.contains(':'))
        .flat_map(|line| line.chars().filter(|c| !c.is_whitespace()))
        .collect();
    B64.decode(body).map_err(|_| CoreError::Malformed("this transfer is damaged or cut short".into()))
}

fn wrong_code() -> CoreError {
    CoreError::DecryptFailed("the code does not open this transfer".into())
}
